export const images = {
  himsPack: require("../../assets/himsPack.png"),
  _3dDoctor: require("../../assets/3dDoctor.png"),
  doctor: require("../../assets/doctor.png"),
  boy_doctor: require("../../assets/boy_doctor.png"),
  doctor_burno: require("../../assets/doctor_burno.jpg"),
  startVisit: require("../../assets/startVisit.jpg"),
  questionIntroOne: require("../../assets/question_images/one.jpg"),
  medHistory: require("../../assets/question_images/medHistory.jpg"),
  happyCouple: require("../../assets/happyCouple.png"),
  afro: require("../../assets/afro.jpg"),
  announcement: require("../../assets/announcement.jpg"),
  tropical: require("../../assets/products/tropical.png"),
  gummies: require("../../assets/products/gummies.png"),
  clean: require("../../assets/products/clean.png"),
  sleep: require("../../assets/products/sleep.png"),
  skin: require("../../assets/products/skin.png"),
  blog1: require("../../assets/blog/blog1.png"),
  blog2: require("../../assets/blog/blog2.png"),
  blog3: require("../../assets/blog/blog3.png"),
};
